# =============================================================================
# r-messy-data-import - SOLUTIONS
# -----------------------------------------------------------------------------
# Every step prints the expected result in a comment. Run the whole file:
#   source("solutions.R")
# Working directory must contain the data/ folder.
# =============================================================================

library(readr)
library(tidyr)
library(dplyr)
library(stringr)

# -----------------------------------------------------------------------------
# Exercise 2.1 - Hospital cost data with a broken DRG column
# -----------------------------------------------------------------------------

# a) Import with skip = 2 (drop the metadata title line AND the header row,
#    because we provide our own col_names)
names <- c("DRG", "ProviderID", "Name", "Address", "City", "State", "ZIP",
           "Region", "Discharges", "AverageCharges", "AverageTotalPayments",
           "AverageMedicarePayments")
inpatient <- read_tsv("data/medicare_hospital_costs.tsv",
                      skip = 2,
                      col_names = names,
                      col_types = "ccccccccnnnn")
inpatient                     # 7 rows x 12 columns; DRG still merged

# b) Split DRG into code + description (code = first 4 characters)
inpatient_separate <- separate(inpatient, DRG,
                               into = c("DRGcode", "DRGdescription"),
                               sep = 4)
inpatient_separate$DRGcode[1]        # [1] "460 "        (trailing space)

# c) Trim the DRGcode field
inpatient_separate$DRGcode <- str_trim(inpatient_separate$DRGcode)
inpatient_separate$DRGcode           # [1] "460" "291" "460" "194" "291" "460" "194"

# d) Remove the "- " prefix from the description
inpatient_separate$DRGdescription <- str_remove(inpatient_separate$DRGdescription, "^- ")
inpatient_separate$DRGdescription    # [1] "SPINAL FUSION EXCEPT CERVICAL WITHOUT MCC" ...

# e) Answers
n_distinct(inpatient_separate$DRGcode)          # [1] 3
inpatient_separate %>%
  arrange(desc(AverageCharges)) %>%
  slice(1) %>% pull(Name)                       # [1] "MEMORIAL SLOAN CLINIC"
# Highest AverageCharges = 51220.90

# -----------------------------------------------------------------------------
# Exercise 2.2 - The broken employee file
# -----------------------------------------------------------------------------

# a) Inspect the raw file
raw <- readLines("data/employees_broken2.txt")
raw[1:3]                    # [1] "HR PAYROLL EXPORT - generated by payroll-system v3.2 on 2025-01-10"
                            # [2] "columns: id;name;birthdate;gender;salary"
                            # [3] "001;Marie Curie;1985-03-14;F;58000"
# Type: semicolon-separated text. Lines 1-2 are METADATA, line 3 onwards is DATA.

# b) Import the data part, everything as character
employees <- read_delim("data/employees_broken2.txt",
                        delim = ";",
                        skip = 2,
                        col_names = c("id", "name", "birthdate", "gender", "salary"),
                        col_types = "ccccc")
employees                    # 7 rows x 5 columns

# c) Validate the id column
employees$id
grepl("^[0-9]{3}$", employees$id)   # [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE

# d) Clean the name: drop quotes, squash whitespace
employees$name <- str_remove_all(employees$name, "[\"']")
employees$name <- str_squish(employees$name)
employees$name               # [1] "Marie Curie" "Nikola Tesla" "Ada Lovelace" ...

# e) Clean the birthdate: detect the two formats and convert to Date
#    YYYY-MM-DD  -> as.Date(x)
#    DD/MM/YYYY  -> as.Date(x, format = "%d/%m/%Y")
employees$birthdate_clean <-
  as.Date(
    ifelse(grepl("^[0-9]{4}-[0-9]{2}-[0-9]{2}$", employees$birthdate),
           employees$birthdate,                       # already ISO
           format(as.Date(employees$birthdate, format = "%d/%m/%Y"), "%Y-%m-%d")),
    format = "%Y-%m-%d"
  )
employees$birthdate_clean    # [1] "1985-03-14" "1856-07-14" "1815-12-10" ...
class(employees$birthdate_clean)   # [1] "Date"

# f) Clean the gender
employees$gender <- ifelse(employees$gender %in% c("F", "Female"), "F",
                    ifelse(employees$gender %in% c("M", "Male"), "M", NA))
employees$gender              # [1] "F" "M" "F" "M" "F" "F" "M"

# g) Clean the salary and flag quality issues
employees$salary_clean <- as.numeric(str_remove_all(employees$salary, "[$, ]"))
employees$salary_flag <- ifelse(employees$salary_clean == 0,
                                "data quality issue (salary = 0)", "ok")
employees$salary_clean        # [1] 58000 72000     0 64000 81000 78000 55000
employees$salary_flag         # [1] "ok" "ok" "data quality issue (salary = 0)" ...
# Ada Lovelace has salary 0 -> real data error, not a real zero.

# -----------------------------------------------------------------------------
# Exercise 2.3 - Foreign aid dataset
# -----------------------------------------------------------------------------

# a) Import (the file HAS a header row)
aid <- read_tsv("data/foreign_aid.tsv")
aid                          # 15 rows x 4 columns
# Amount was guessed as character because of "$" and "(45,000)".

# b) Clean the country column
aid$country_clean <- case_when(
  grepl("South|^S\\.|Republic", aid$Country) ~ "South Korea",
  grepl("North|^N\\.|DPRK", aid$Country)     ~ "North Korea",
  TRUE                                        ~ aid$Country
)
table(aid$country_clean)     # Brazil 1, France 1, Germany 1, India 1, Japan 1,
                             # Kenya 1, North Korea 3, South Korea 4, USA 1,
                             # United Kingdom 1

# c) Clean the agency and count unique agencies
aid$agency_clean <- case_when(
  aid$FundingAgency %in% c("UN Development Programme", "UNDP") ~ "UNDP",
  TRUE                                                          ~ aid$FundingAgency
)
agency <- n_distinct(aid$agency_clean)
agency                       # [1] 8
sort(unique(aid$agency_clean))
# [1] "Asian Development Bank" "European Union"         "Green Climate Fund"
# [4] "UNDP"                   "USAID"                  "WHO"
# [7] "World Bank"             "World Food Programme"

# d) FundingAmount to numeric WITHOUT creating NAs
#    Step 1: drop "$", "USD", commas and spaces
tmp <- str_remove_all(aid$FundingAmount, "[$,USD ]")
#    Step 2: turn "(45,000)"-style parentheses into a negative sign
tmp <- ifelse(grepl("^\\(.*\\)$", tmp),
              paste0("-", str_remove_all(tmp, "[\\(\\)]")),
              tmp)
#    Step 3: convert
aid$amount_num <- as.numeric(tmp)
aid$amount_num                # [1]  1234567.0 200000.0 500000.0 320000.0 ...
                              # [7] -45000.0 12500000.0 2000000.0 ...
sum(is.na(aid$amount_num))    # [1] 1  <- only the deliberate "n/a" (Kenya)
# Every parseable value survived; only the literal "n/a" stays NA on purpose.

# e) Frequency table of the cleaned country column
freq <- table(aid$country_clean)
freq
freq["South Korea"]           # 4
freq["North Korea"]           # 3
